### ISSUE TITLE
Edit `todo`

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/ms-todo#4]
#### UI 
- Edit form for `todo`
  - [ ] Modal 
  - [ ] Fields `name`, `description`, and `due date`
#### Backend 
- [ ] Make `/edit-todo/{id}` `POST`
- [ ] Enter into database
